[package]
name = "wind"
version = "0.1.0"
authors = ["Oscar Moreno <oscarmg99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cm-telemetry = "2.2.0"
gpioduino = "0.1.0"